
import React, { useState, useEffect } from 'react';
import { FileText, Download, Calendar, Search, Loader2, FileSpreadsheet, FileCode, FileType } from 'lucide-react';
import { useToast } from './Toast';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

interface ReportTemplate {
  id: number;
  name: string;
  description: string;
  category: string;
}

interface ReportCenterProps {
  userRole: string;
  userEmail: string;
}

export const ReportCenter: React.FC<ReportCenterProps> = ({ userRole, userEmail }) => {
  const { addToast } = useToast();
  const [templates, setTemplates] = useState<ReportTemplate[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isGenerating, setIsGenerating] = useState<number | null>(null);
  const [preset, setPreset] = useState('monthly');
  const [dateRange, setDateRange] = useState({
    start: new Date(new Date().setDate(new Date().getDate() - 30)).toISOString().split('T')[0],
    end: new Date().toISOString().split('T')[0]
  });

  const handlePresetChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
    const value = e.target.value;
    setPreset(value);
    
    if (value === 'custom') return;

    const end = new Date();
    const start = new Date();
    
    if (value === 'weekly') start.setDate(end.getDate() - 7);
    else if (value === 'monthly') start.setDate(end.getDate() - 30);
    else if (value === 'quarterly') start.setDate(end.getDate() - 90);
    else if (value === 'yearly') start.setDate(end.getDate() - 365);
    
    setDateRange({
      start: start.toISOString().split('T')[0],
      end: end.toISOString().split('T')[0]
    });
  };

  useEffect(() => {
    fetchTemplates();
  }, []);

  const fetchTemplates = async () => {
    try {
      const res = await fetch('/api/admin/reports/templates', {
        headers: { 'x-user-role': userRole, 'x-user-email': userEmail }
      });
      if (res.ok) {
        const data = await res.json();
        setTemplates(data);
      }
    } catch (error) {
      addToast('error', 'Failed to load report templates');
    } finally {
      setIsLoading(false);
    }
  };

  const handleGenerate = async (templateId: number, name: string, format: 'csv' | 'json' | 'pdf') => {
    setIsGenerating(templateId);
    try {
      const res = await fetch(`/api/admin/reports/generate/${templateId}`, {
        method: 'POST',
        headers: { 
          'Content-Type': 'application/json',
          'x-user-role': userRole, 
          'x-user-email': userEmail 
        },
        body: JSON.stringify({ dateRange, format })
      });

      if (res.ok) {
        if (format === 'csv') {
          const blob = await res.blob();
          const url = window.URL.createObjectURL(blob);
          const a = document.createElement('a');
          a.href = url;
          a.download = `${name}_${dateRange.start}_to_${dateRange.end}.csv`;
          document.body.appendChild(a);
          a.click();
          a.remove();
        } else if (format === 'pdf') {
          const data = await res.json();
          generateNativePDF(name, data);
        } else {
          const data = await res.json();
          const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
          const url = window.URL.createObjectURL(blob);
          const a = document.createElement('a');
          a.href = url;
          a.download = `${name}_${dateRange.start}_to_${dateRange.end}.json`;
          document.body.appendChild(a);
          a.click();
          a.remove();
        }
        addToast('success', 'Report generated successfully');
      } else {
        addToast('error', 'Failed to generate report');
      }
    } catch (error) {
      addToast('error', 'Network error generating report');
    } finally {
      setIsGenerating(null);
    }
  };

  const generateNativePDF = (title: string, data: any[]) => {
    const doc = new jsPDF();
    const now = new Date();
    const timestampStr = now.toLocaleString();
    const unixTimestamp = now.getTime();

    const drawFooter = (docInstance: jsPDF, pageNum: number) => {
      const pageSize = docInstance.internal.pageSize;
      const pageHeight = pageSize.height ? pageSize.height : pageSize.getHeight();
      
      // Draw border line above footer
      docInstance.setDrawColor(226, 232, 240); // slate-200
      docInstance.line(14, pageHeight - 20, pageSize.width - 14, pageHeight - 20);

      docInstance.setFontSize(8);
      docInstance.setTextColor(148, 163, 184); // slate-400
      
      // Footer Left: Branding + Timestamp
      docInstance.text(`Generated by ZatcaConnect | ${timestampStr} | TS: ${unixTimestamp}`, 14, pageHeight - 12);
      
      // Footer Right: Page Number
      const str = `Page ${pageNum}`;
      docInstance.text(str, pageSize.width - 25, pageHeight - 12);
    };

    // Add Header
    doc.setFontSize(22);
    doc.setTextColor(15, 23, 42); // slate-900
    doc.text(title.toUpperCase(), 14, 22);
    
    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139); // slate-500
    doc.text(`Audit Period: ${dateRange.start} to ${dateRange.end}`, 14, 30);

    if (!data || data.length === 0) {
      doc.setFontSize(12);
      doc.setTextColor(100, 116, 139);
      doc.text('No data available for the selected period.', 14, 50);
      drawFooter(doc, 1);
    } else {
      const headers = Object.keys(data[0]).map(key => key.replace(/_/g, ' ').toUpperCase());
      const body = data.map(row => Object.values(row).map(val => val === null || val === undefined ? '-' : String(val)));

      autoTable(doc, {
        startY: 40,
        head: [headers],
        body: body,
        theme: 'striped',
        headStyles: { 
          fillColor: [15, 23, 42], 
          textColor: [255, 255, 255], 
          fontSize: 8, 
          fontStyle: 'bold'
        },
        bodyStyles: { 
          fontSize: 7, 
          textColor: [51, 65, 85] 
        },
        margin: { top: 40, bottom: 25 },
        didDrawPage: (hookData) => {
          drawFooter(doc, hookData.pageNumber);
        }
      });
    }

    doc.save(`${title.replace(/\s+/g, '_')}_${unixTimestamp}.pdf`);
  };

  return (
    <div className="p-8 max-w-7xl mx-auto space-y-8 animate-in fade-in duration-500">
      <div className="flex justify-between items-end">
        <div>
          <h1 className="text-3xl font-bold text-slate-900 tracking-tight">Report Center</h1>
          <p className="text-slate-500 mt-2 text-lg">Generate and download audit reports for your organization.</p>
        </div>
        
        <div className="flex items-end gap-4 bg-white p-4 rounded-2xl shadow-sm border border-slate-100">
          <div className="space-y-1">
            <label className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block ml-1">Quick Period</label>
            <select 
              value={preset}
              onChange={handlePresetChange}
              className="px-3 py-2 bg-slate-50 border border-slate-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-indigo-500/20 text-sm font-medium text-slate-700 outline-none"
            >
              <option value="weekly">Weekly (Last 7 Days)</option>
              <option value="monthly">Monthly (Last 30 Days)</option>
              <option value="quarterly">Quarterly (Last 90 Days)</option>
              <option value="yearly">Yearly (Last 365 Days)</option>
              <option value="custom">Custom Range</option>
            </select>
          </div>
          <div className="space-y-1">
            <label className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block ml-1">Start Date</label>
            <input 
              type="date" 
              value={dateRange.start}
              onChange={e => { setPreset('custom'); setDateRange({...dateRange, start: e.target.value}); }}
              className="px-3 py-2 bg-slate-50 border border-slate-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-indigo-500/20 text-sm"
            />
          </div>
          <div className="space-y-1">
            <label className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block ml-1">End Date</label>
            <input 
              type="date" 
              value={dateRange.end}
              onChange={e => { setPreset('custom'); setDateRange({...dateRange, end: e.target.value}); }}
              className="px-3 py-2 bg-slate-50 border border-slate-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-indigo-500/20 text-sm"
            />
          </div>
        </div>
      </div>

      {isLoading ? (
        <div className="flex justify-center py-20">
          <Loader2 className="animate-spin text-slate-300" size={48} />
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {templates.map(template => (
            <div key={template.id} className="group bg-white rounded-3xl p-6 border border-slate-200 shadow-sm hover:shadow-xl hover:-translate-y-1 transition-all duration-300 relative overflow-hidden">
              <div className="absolute top-0 right-0 p-4 opacity-10 group-hover:opacity-20 transition-opacity">
                <FileText size={80} />
              </div>
              
              <div className="relative">
                <div className="w-12 h-12 rounded-2xl bg-indigo-50 flex items-center justify-center text-indigo-600 mb-4 group-hover:scale-110 transition-transform">
                  <FileText size={24} />
                </div>
                
                <h3 className="text-xl font-bold text-slate-800 mb-2 truncate pr-8">{template.name}</h3>
                <p className="text-slate-500 text-sm line-clamp-2 mb-6 h-10">{template.description || 'No description provided.'}</p>
                
                <div className="flex flex-col gap-2 pt-4 border-t border-slate-50">
                  <div className="flex gap-2">
                    <button 
                      disabled={isGenerating !== null}
                      onClick={() => handleGenerate(template.id, template.name, 'csv')}
                      className="flex-1 flex items-center justify-center gap-2 px-4 py-2.5 bg-slate-900 text-white rounded-xl hover:bg-slate-800 disabled:opacity-50 transition-colors text-sm font-bold shadow-lg shadow-slate-900/10"
                    >
                      {isGenerating === template.id ? <Loader2 className="animate-spin" size={16} /> : <FileSpreadsheet size={16} />}
                      CSV
                    </button>
                    <button 
                      disabled={isGenerating !== null}
                      onClick={() => handleGenerate(template.id, template.name, 'json')}
                      className="flex-1 flex items-center justify-center gap-2 px-4 py-2.5 bg-white border border-slate-200 text-slate-700 rounded-xl hover:bg-slate-50 disabled:opacity-50 transition-colors text-sm font-bold"
                    >
                      {isGenerating === template.id ? <Loader2 className="animate-spin" size={16} /> : <FileCode size={16} />}
                      JSON
                    </button>
                  </div>
                  <button 
                    disabled={isGenerating !== null}
                    onClick={() => handleGenerate(template.id, template.name, 'pdf')}
                    className="w-full flex items-center justify-center gap-2 px-4 py-2.5 bg-indigo-50 border border-indigo-100 text-indigo-700 rounded-xl hover:bg-indigo-100 disabled:opacity-50 transition-colors text-sm font-bold"
                  >
                    {isGenerating === template.id ? <Loader2 className="animate-spin" size={16} /> : <FileType size={16} />}
                    Download PDF Report
                  </button>
                </div>
              </div>
            </div>
          ))}

          {templates.length === 0 && (
            <div className="col-span-full bg-slate-50 rounded-3xl p-20 text-center border-2 border-dashed border-slate-200">
               <div className="w-20 h-20 rounded-full bg-white flex items-center justify-center text-slate-300 mx-auto mb-6 shadow-sm">
                  <FileText size={40} />
               </div>
               <h3 className="text-xl font-bold text-slate-700">No Templates Available</h3>
               <p className="text-slate-500 mt-2 max-w-sm mx-auto">Please contact your system administrator to design and assign report templates for your account.</p>
            </div>
          )}
        </div>
      )}
    </div>
  );
};
