csr.common.name=Test
csr.serial.number=1-TS|2-T|3-ed22f1d8-e6a2-1118-9b58-d9a8f11e445f
csr.organization.identifier=312345678901233
csr.organization.unit.name=Main
csr.organization.name=Test Co
csr.country.name=SA
csr.invoice.type=1100
csr.location.address=Riyadh
csr.industry.business.category=IT
