import prisma from '../server/src/lib/prisma.js';
import { SecurityService } from '../server/src/services/securityService.js';
import { validateCertKeyPair } from '../server/src/services/complianceService.js';
import axios from 'axios';
import 'dotenv/config';

async function auditProductionCredentials() {
    console.log('========================================================');
    console.log('🔍 CREDENTIAL PROVENANCE & BASIC AUTH AUDIT');
    console.log('========================================================\n');

    const vatNumber = process.env.VAT_NUMBER || '311499218600003';

    // 1. Fetch active PRODUCTION certificate record
    const certRecord = await prisma.certificate.findFirst({
        where: {
            company: { vat_number: vatNumber },
            type: 'PRODUCTION',
            is_active: true
        },
        include: { company: true }
    });

    if (!certRecord) {
        console.error('❌ Active Production certificate record NOT FOUND in DB for VAT:', vatNumber);
        process.exit(1);
    }

    console.log(`[Record Selection Audit] Selected Active Record ID: ${certRecord.id}`);
    console.log(`[Record Selection Audit] Company: ${certRecord.company.registered_name} (VAT: ${certRecord.company.vat_number})`);
    console.log(`[Record Selection Audit] Environment Type: ${certRecord.type}`);
    console.log(`[Record Selection Audit] Created At: ${certRecord.created_at?.toISOString()}`);

    // Provenance Check: Was this generated by simulation onboarding or mock data?
    const isMockOrSim = certRecord.csid?.startsWith('MOCK_') || certRecord.common_name?.toLowerCase().includes('sim');
    console.log(`[Provenance Audit] Customer-Issued Production Credential Provenance: ${isMockOrSim ? '❌ NO (Placeholder/Simulation Token in DB)' : '✅ YES (Imported Production Credential)'}`);

    // Decryption Check for Secret
    let decryptedSecret = '';
    let secretDecryptedOk = false;
    try {
        if (certRecord.secret) {
            decryptedSecret = certRecord.secret.includes(':') 
                ? SecurityService.decrypt(certRecord.secret) 
                : certRecord.secret;
            secretDecryptedOk = decryptedSecret.length > 0;
        }
    } catch (e: any) {
        console.error('[Decryption Audit] Secret Decryption Failed:', e.message);
    }
    console.log(`[Decryption Audit] Production Secret Decryption: ${secretDecryptedOk ? '✅ PASSED' : '❌ FAILED'}`);

    // Decryption Check for Private Key
    let decryptedKey = '';
    let keyDecryptedOk = false;
    try {
        if (certRecord.private_key) {
            decryptedKey = certRecord.private_key.includes(':') 
                ? SecurityService.decrypt(certRecord.private_key) 
                : certRecord.private_key;
            keyDecryptedOk = decryptedKey.length > 0;
        }
    } catch (e: any) {
        console.error('[Decryption Audit] Private Key Decryption Failed:', e.message);
    }
    console.log(`[Decryption Audit] Production Private Key Decryption: ${keyDecryptedOk ? '✅ PASSED' : '❌ FAILED'}`);

    // Cryptographic Pairing Check (Cert vs Private Key)
    let keypairValid = false;
    if (certRecord.csid && decryptedKey) {
        keypairValid = validateCertKeyPair(certRecord.csid, decryptedKey);
    }
    console.log(`[Cryptographic Audit] Cert & Private Key Match: ${keypairValid ? '✅ PASSED' : '❌ FAILED'}`);

    // Basic Auth Encoding Integrity Check (Whitespace, Newline, Truncation)
    const rawCsid = certRecord.csid || '';
    const cleanCsid = rawCsid.replace(/-----BEGIN CERTIFICATE-----/g, '')
                             .replace(/-----END CERTIFICATE-----/g, '')
                             .replace(/[\r\n\s]/g, '');

    const cleanSecret = decryptedSecret.trim();
    const hasControlChars = /[\r\n]/.test(cleanCsid) || /[\r\n]/.test(cleanSecret);
    const authHeaderValue = 'Basic ' + Buffer.from(`${cleanCsid}:${cleanSecret}`).toString('base64');
    const authConstructionOk = authHeaderValue.length > 10 && !hasControlChars;

    console.log(`[Encoding Audit] CSID Clean Base64 Length: ${cleanCsid.length} bytes`);
    console.log(`[Encoding Audit] Secret Length: ${cleanSecret.length} bytes`);
    console.log(`[Encoding Audit] Control Characters Removed: ${!hasControlChars ? '✅ YES' : '❌ NO'}`);
    console.log(`[Encoding Audit] Basic Auth Header Construction: ${authConstructionOk ? '✅ VALID (Basic Base64[CSID:Secret])' : '❌ INVALID'}`);

    // 2. Production Gateway Authentication Probe
    console.log('\n--- EXECUTING PRODUCTION API AUTHENTICATION PROBE ---');
    const prodUrl = 'https://gw-fatoora.zatca.gov.sa/e-invoicing/core/invoices/clearance/single';
    console.log(`Endpoint            : ${prodUrl}`);
    console.log(`HTTP Method         : POST`);
    console.log(`Sanitized Headers   : Accept-Version: V2, Content-Type: application/json, Authorization: Basic [REDACTED]`);

    const probeBody = {
        invoiceHash: 'probe_connectivity_check_hash',
        uuid: '00000000-0000-0000-0000-000000000000',
        invoice: 'cHJvYmVfY29ubmVjdGl2aXR5X2NoZWNr'
    };

    let httpStatus = 0;
    let zatcaCorrelationId = 'N/A';
    let responseData: any = null;
    let explicitAuthAccepted = false;

    try {
        const res = await axios.post(prodUrl, probeBody, {
            headers: {
                'Authorization': authHeaderValue,
                'Accept-Version': 'V2',
                'Content-Type': 'application/json',
                'Accept-Language': 'en'
            },
            validateStatus: () => true
        });

        httpStatus = res.status;
        zatcaCorrelationId = (res.headers['x-request-id'] || res.headers['correlation-id'] || 'N/A') as string;
        responseData = res.data;

        // Explicit Auth Validation Logic (Not naive HTTP != 401)
        // Authentic ZATCA authorization returns 200/202 OR 400 schema error on invoice body
        if (httpStatus === 200 || httpStatus === 202 || (httpStatus === 400 && responseData?.code !== 'Unauthorized')) {
            explicitAuthAccepted = true;
        }
    } catch (e: any) {
        console.error('❌ Network Probe Failure:', e.message);
    }

    console.log('\n========================================================');
    console.log('📡 SANITIZED AUDIT & PROBE REPORT');
    console.log('========================================================');
    console.log(`Credential Record ID : ${certRecord.id}`);
    console.log(`HTTP Status Code     : ${httpStatus}`);
    console.log(`ZATCA Correlation ID : ${zatcaCorrelationId}`);
    console.log(`Endpoint & Method    : POST ${prodUrl}`);
    console.log(`Sanitized Response   :`, JSON.stringify(responseData || '').substring(0, 200));
    console.log(`Customer Provenance  : ${isMockOrSim ? '❌ Placeholder/Simulation Token' : '✅ Customer-Issued Production Credential'}`);
    console.log(`ZATCA Auth Result    : ${explicitAuthAccepted ? '✅ AUTHENTICATION ACCEPTED' : '❌ AUTHENTICATION REJECTED (HTTP 401/403)'}`);
    console.log('========================================================\n');

    if (!explicitAuthAccepted) {
        console.log('⚠️ Verification Notice: Production API returned HTTP 401. Current active record contains placeholder credentials.');
        console.log('⚠️ B2B Clearance and B2C Reporting invoice submissions will remain strictly locked until customer-issued Production credentials are imported.');
    }
}

auditProductionCredentials().catch(console.error).finally(() => prisma.$disconnect());
